<?php

namespace MainBundle\Repository;

/**
 * OffreVoyageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffreVoyageRepository extends \Doctrine\ORM\EntityRepository
{
}
